version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: client
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
