version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: client
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - piscord_network
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - piscord_network
  db:
    container_name: database
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - db_piscord:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - piscord_network

volumes:
  db_piscord:


networks:
  piscord_network:
