import { Router } from "express";
import { loginUser, signupUser } from "../controllers/authController";
import { verifyAccount } from "../middlewares/verifyAccount";
import { prisma } from "../db/db";
import { validateSignUp } from "../validation/signUpValidation";
const authRouter = Router();
authRouter.post("/signup",validateSignUp(), signupUser);
authRouter.post("/login", loginUser);
authRouter.post("/verify/:token", verifyAccount);
export default authRouter;
